version: "3.8"
services:

  nginx:
    container_name: nginx
    depends_on:
      - backend
      - frontend1
      - frontend2
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"

  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8765"
      
  frontend1:
    container_name: frontend1
    restart: always
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - FRONTENDNAME=WEB1

  frontend2:
    container_name: frontend2
    restart: always
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - FRONTENDNAME=WEB2